@set allusersprofile=c:\programdata
@set appdata=c:\users\danie\appdata\roaming
@set classpath=c:\program files\java\jdk-14.0.1\lib
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=hqzsc72-06d9
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\
@set homedrive=c:
@set homepath=\users\danie
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set ifcpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\ifc\x64
@set include=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\include;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\shared;c:\program files (x86)\windows kits\10\include\10.0.18362.0\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\cppwinrt
@set lib=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\danie\appdata\local
@set logonserver=\\hqzsc72-06d9
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=8
@set onedrive=c:\users\danie\onedrive
@set onedriveconsumer=c:\users\danie\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\\extensions\microsoft\intellicode\cli;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files (x86)\microsoft sdks\azure\cli2\wbin;c:\program files\slickeditv17.0.3 x64\win\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\putty\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files (x86)\gitextensions\;c:\program files (x86)\incredibuild;c:\program files\docker\docker\resources\bin;c:\programdata\dockerdesktop\version-bin;c:\program files\tortoisesvn\bin;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\matlab\r2016b\bin;c:\program files\java\jdk-14.0.1\bin;c:\program files\dotnet\;c:\program files\conan\conan;c:\users\danie\appdata\local\microsoft\windowsapps;c:\users\danie\appdata\local\githubdesktop\bin;c:\users\danie\appdata\local\microsoft\windowsapps;c:\users\danie\appdata\local\programs\microsoft vs code\bin;c:\users\danie\.dotnet\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\linux\bin\connectionmanagerexe
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\danie\appdata\local\microsoft\visualstudio\16.0_a6a13d2d\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 94 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=5e03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules;c:\program files\intel\
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\community
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\3.1.401\sdks
@set servicehublogsessionkey=7845bb80
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\danie\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\danie\appdata\local\temp
@set ucrtversion=10.0.18362.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=hqzsc72-06d9
@set userdomain_roamingprofile=hqzsc72-06d9
@set username=danie
@set userprofile=c:\users\danie
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\
@set vcpkg_default_triplet=x64-windows
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\community\vc\redist\msvc\14.27.29016\
@set vctoolsversion=14.27.29110
@set visualstudiodir=c:\users\danie\documents\visual studio 2019
@set visualstudioedition=microsoft visual studio community 2019
@set visualstudioversion=16.0
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=16.7.2
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\
@set vslang=1033
@set vssdk150install=c:\program files (x86)\microsoft visual studio\2019\community\vssdk
@set vssdkinstall=c:\program files (x86)\microsoft visual studio\2019\community\vssdk
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.18362.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.18362.0\
@set windowssdkversion=10.0.18362.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files (x86)\microsoft sdks\azure\cli2\wbin;c:\program files\slickeditv17.0.3 x64\win\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\putty\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files (x86)\gitextensions\;c:\program files (x86)\incredibuild;c:\program files\docker\docker\resources\bin;c:\programdata\dockerdesktop\version-bin;c:\program files\tortoisesvn\bin;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\matlab\r2016b\bin;c:\program files\java\jdk-14.0.1\bin;c:\program files\dotnet\;c:\program files\conan\conan;c:\users\danie\appdata\local\microsoft\windowsapps;c:\users\danie\appdata\local\githubdesktop\bin;c:\users\danie\appdata\local\microsoft\windowsapps;c:\users\danie\appdata\local\programs\microsoft vs code\bin;c:\users\danie\.dotnet\tools
@set __vscmd_script_err_count=0

@call "cl.exe" @"C:\Users\danie\Documents\GitHub\jsoncons\tests\decode_msgpack_tests.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1